routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/*
Route::get('/', function () {
    return view('welcome');
});
*/
Route::resource('tips', 'TipsController');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Tip.php
<?php
/**
 * Created by PhpStorm.
 * User: SREEPARNA
 * Date: 2019-02-25
 * Time: 16:06
 */
namespace App;

use Illuminate\Database\Eloquent\Model;

class Tip extends Model
{
    protected $table = 'tips';
    protected $guarded = array();

    public function getData()
    {
        return static::orderBy('id', 'desc')->paginate(5);
    }

    public function AddData($input)
    {
        return static::create($input);
    }

    public function findData($id)
    {
        return static::find($id);
    }

    public function updateData($id, $input)
    {
        return static::where('id', $id)->update($input);
    }

    public function destroyData($id)
    {
        return static::where('id',$id)->delete();
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/TipsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests;
use Illuminate\Http\Request;
use App\Tip;

class TipsController extends HomeController
{
    public function __construct()
    {
        parent::__construct();

        $this->Tip = new Tip;

        $this->moduleTitleS = 'Tips';
        $this->moduleTitleP = 'Tips';

        view()->share('moduleTitleP',$this->moduleTitleP);
        view()->share('moduleTitleS',$this->moduleTitleS);
    }

    public function index()
    {
        $data = $this->Tip->getData();

        return view($this->moduleTitleP.'.index',compact('data'))
            ->with('i',0);
    }

    public function create()
    {
        return view('tips.create');
      /*  $this->validate($request, [
            'title' => 'required|max:255',
            'tips' => 'required',
        ]);

        $input = array_except($request->all(),array('_token'));

        $this->Tip->AddData($input);

        \Session::put('success','Tip Store Successfully!!');

        return redirect()->route('tips.index');*/
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'title' => 'required|max:255',
            'tips' => 'required',
        ]);

        $input = array_except($request->all(), array('_token'));

        $this->Tip->AddData($input);

        \Session::put('success', 'Tip Store Successfully!!');

        return redirect()->route('tips.index');
    }
    public function edit($id)
    {
        $data = $this->Tip->findData($id);

        return view($this->moduleTitleP.'.edit',compact('data'));
    }

    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'title' => 'required|max:255',
            'tips' => 'required',
        ]);

        $input = array_except($request->all(),array('_token', '_method'));

        $this->Tip->updateData($id, $input);

        \Session::put('success','Tip Updated Successfully!!');

        return redirect()->route('tips.index');
    }

    public function destroy($id)
    {
        $this->Tip->destroyData($id);

        \Session::put('success','Post Delete Successfully!!');

        return redirect()->route('tips.index');
    }
}

resources/views/Tips/create.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: SREEPARNA
 * Date: 2019-02-25
 * Time: 16:16
 */
?>
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-default">
                    <div class="panel-heading">Create Tip</div>
                    <div class="panel-body">
                        <form class="form-horizontal" method="POST" action="{{ route('tips.store') }}">
                            {{ csrf_field() }}
                            <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
                                <label for="title" class="col-md-3 control-label">Title</label>
                                <div class="col-md-7">
                                    <input id="title" type="text" class="form-control" name="title" value="{{ old('title') }}" required autofocus>
                                    @if ($errors->has('title'))
                                        <span class="help-block">
                <strong>{{ $errors->first('title') }}</strong>
                </span>
                                    @endif
                                </div>
                            </div>
                            <div class="form-group{{ $errors->has('tips') ? ' has-error' : '' }}">
                                <label for="tips" class="col-md-3 control-label">Tips Description</label>
                                <div class="col-md-7">
                                    <textarea id="tips" rows="6" class="form-control" name="tips" required>{{ old('tips') }}</textarea>
                                    @if ($errors->has('tips'))
                                        <span class="help-block">
                <strong>{{ $errors->first('tips') }}</strong>
                </span>
                                    @endif
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-7 col-md-offset-3">
                                    <button type="submit" class="btn btn-primary btn-block">
                                        Submit
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
<?php
/*
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-default">
                    <div class="panel-heading">Create Tip</div>
                    <div class="panel-body">
                        <form class="form-horizontal" method="POST" action="{{ route('tips.store') }}">
                            {{ csrf_field() }}
                            <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
                                <label for="title" class="col-md-3 control-label">Title</label>
                                <div class="col-md-7">
                                    <input id="title" type="text" class="form-control" name="title" value="{{ old('title') }}" required autofocus>
                                    @if ($errors->has('title'))
                                        <span class="help-block">
                <strong>{{ $errors->first('title') }}</strong>
                </span>
                                    @endif
                                </div>
                            </div>
                            <div class="form-group{{ $errors->has('tips') ? ' has-error' : '' }}">
                                <label for="tips" class="col-md-3 control-label">Tips Description</label>
                                <div class="col-md-7">
                                    <textarea id="tips" rows="6" class="form-control" name="tips" required>{{ old('tips') }}</textarea>
                                    @if ($errors->has('tips'))
                                        <span class="help-block">
                <strong>{{ $errors->first('tips') }}</strong>
                </span>
                                    @endif
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-7 col-md-offset-3">
                                    <button type="submit" class="btn btn-primary btn-block">
                                        Submit
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection */
?>

resources/views/Tips/edit.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: SREEPARNA
 * Date: 2019-02-25
 * Time: 16:16
 */
?>
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-default">
                    <div class="panel-heading">Edit Tip</div>
                    <div class="panel-body">
                      <?php //  {{ Form::model($data, ['route' => ['tips.update', $data->id], 'method' => 'patch', 'class' =>'form-horizontal']) }}
                        ?>
                          <form action="{{ route('tips.update', $data->id)}}" method="post">
                              @csrf
                              @method('PATCH')

                        <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
                            <label for="title" class="col-md-3 control-label">Title</label>
                            <div class="col-md-7">
                                <input id="title" type="text" class="form-control" name="title" value="{{ $data->title }}" required autofocus>
                                @if ($errors->has('title'))
                                    <span class="help-block">
              <strong>{{ $errors->first('title') }}</strong>
              </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group{{ $errors->has('tips') ? ' has-error' : '' }}">
                            <label for="tips" class="col-md-3 control-label">Tips Description</label>
                            <div class="col-md-7">
                                <textarea id="tips" rows="6" class="form-control" name="tips" required>{{ $data->tips }}</textarea>
                                @if ($errors->has('tips'))
                                    <span class="help-block">
              <strong>{{ $errors->first('tips') }}</strong>
              </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-7 col-md-offset-3">
                                <button type="submit" class="btn btn-primary btn-block">
                                    Update
                                </button>
                            </div>
                        </div>
                        </form>
                      <?php // {{ Form::close() }} ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/Tips/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <div class="row">
                            <div class="col-md-10">
                                <strong>All Tips Listing</strong>
                            </div>
                            <div class="col-md-2">
                                <a href="{{ URL::route('tips.create') }}" class="btn btn-info pull-right">Add Tips</a>
                            </div>
                        </div>
                    </div>
                    <div class="panel-body">
                        <table class="table table-bordered">
                            <tr>
                                <th>Title</th>
                                <th width="500">Tips Description</th>
                                <th width="180" class="text-center">Action</th>
                            </tr>
                            @if(!empty($data) && $data->count())
                                @foreach($data as $key => $value)
                                    <tr>
                                        <td>{{ $value->title }}</td>
                                        <td>
                                            @if (strlen($value->tips) > 100)
                                                {!! substr(strip_tags(html_entity_decode($value->tips)), 0, 100) . '.....' !!}
                                            @else
                                                {!! strip_tags($value->tips) !!}
                                            @endif
                                        </td>
                                        <td class="text-center">
                                            <a href="{!! URL::route('tips.edit', $value->id) !!}" class="btn btn-success">Edit</a>
                                            <a data-toggle="modal" data-url="{!! URL::route('tips.destroy', $value->id) !!}" data-id="{{$value->id}}" data-target="#custom-width-modal" class="btn btn-danger remove-record">Delete</a>
                                        </td>
                                    </tr>
                                @endforeach
                            @endif
                        </table>
                    </div>
                </div>
                {!! $data->appends([])->render() !!}
            </div>
        </div>
    </div>
@endsection

resources/views/alert.blade.php
@if ($errors->any())
    <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">×</span>
        </button>
        <strong>Error Alert!</strong> Please check the form below for errors
    </div>
@endif
@if ($message = Session::get('success'))
    <div class="alert alert-success alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">×</span>
        </button>
        <strong>Success Alert!</strong> <?php echo $message; ?>
    </div>
    <?php Session::forget('success');?>
@endif
@if ($message = Session::get('error'))
    <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">×</span>
        </button>
        <strong>Error Alert!</strong> <?php echo $message; ?>
    </div>
    <?php Session::forget('error');?>
@endif
@if ($message = Session::get('warning'))
    <div class="alert alert-warning alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">×</span>
        </button>
        <strong>Waarning Alert!</strong> <?php echo $message; ?>
    </div>
    <?php Session::forget('warning');?>
@endif
@if ($message = Session::get('info'))
    <div class="alert alert-indo alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">×</span>
        </button>
        <strong>Information Alert!</strong> <?php echo $message; ?>
    </div>
    <?php Session::forget('info');?>
@endif

resources/views/deleteModel.blade.php
<form action="" method="POST" class="remove-record-model">
    <div id="custom-width-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="custom-width-modalLabel" aria-hidden="true" style="display: none;">
        <div class="modal-dialog" style="width:55%;">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h4 class="modal-title" id="custom-width-modalLabel">Delete Record</h4>
                </div>
                <div class="modal-body">
                    <h4>You Want You Sure Delete This Record?</h4>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default waves-effect remove-data-from-delete-form" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-danger waves-effect waves-light">Delete</button>
                </div>
            </div>
        </div>
    </div>
</form>

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>{{ config('app.name', 'Laravel') }}</title>
    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <script type="text/javascript">
        var current_page_url = "<?php echo URL::current(); ?>";
        var current_page_fullurl = "<?php echo URL::full(); ?>";
        var CSRF_TOKEN='{{ csrf_token() }}';
    </script>
</head>
<body>
<div id="app">
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">
                <!-- Collapsed Hamburger -->
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse" aria-expanded="false">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- Branding Image -->
                <a class="navbar-brand" href="{{ url('/home') }}">
                    CBTF
                </a>
            </div>
            <div class="collapse navbar-collapse" id="app-navbar-collapse">
                <!-- Left Side Of Navbar -->
                <ul class="nav navbar-nav">

                </ul>
                <!-- Right Side Of Navbar -->
                <ul class="nav navbar-nav navbar-right">
                    <!-- Authentication Links -->
                    @guest
                        <li><a href="{{ route('login') }}">Login</a></li>
                        <li><a href="{{ route('register') }}">Register</a></li>
                    @else
                        <li><a href="{{ URL::route('tips.index') }}">Tips</a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true">
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                      document.getElementById('logout-form').submit();">
                                        Logout
                                    </a>
                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        {{ csrf_field() }}
                                    </form>
                                </li>
                            </ul>
                        </li>
                    @endguest
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                @include('alert')
            </div>
        </div>
    </div>
    @yield('content')
</div>
@include('deleteModel')
<!-- Scripts -->
<script src="{{ asset('js/app.js') }}"></script>
<script src="{{ asset('js/custom.js') }}"></script>
</body>
</html>